using Anthropic.SDK.Messaging;
using Ares.Core.Database.Model.Chat.Sub;
using Ares.Core.Objects.Chat;
using Ares.Core.Objects.Chat.Image;
using DeepSeek.Core.Models;
using OpenAI.Chat;
using OpenAI.Images;

namespace Ares.Core.Util;

public class AiUtil
{
    /// <summary>
    /// <b>General</b> - Constructs a chat history from a given response.
    /// </summary>
    /// <param name="prompt">Input text provided by the user.</param>
    /// <param name="imageUrl">Custom media URL, if available. (Applicable when <paramref name="responseOpenAi"/> or <paramref name="imageOpenAi"/> is not null)</param>
    /// <param name="responseAnthropic">Response generated by Anthropic's AI.</param>
    /// <param name="responseDeepSeek">Response generated by DeepSeek's AI.</param>
    /// <param name="responseOpenAi">Response generated by OpenAI's AI.</param>
    /// <param name="imageOpenAi">Response containing an image generated by OpenAI's AI.</param>
    /// <returns>A list of chat history entries.</returns>
    public static List<GChatHistoricModel> ConvertToChatHistoric(string prompt, string imageUrl = "", MessageResponse? responseAnthropic =  null, ChatResponse? responseDeepSeek = null, ChatCompletion? responseOpenAi = null, GeneratedImage? imageOpenAi = null)
    {
        List<GChatHistoricModel> historics = new List<GChatHistoricModel>();

        if (responseAnthropic != null)
        {
            historics.Add(new GChatHistoricModel
            (
                prompt: prompt,
                response: responseAnthropic.Message.ToString(),
                usage: new ChatValueUsage(responseAnthropic.Usage.OutputTokens, responseAnthropic.Usage.InputTokens)
            ));
        }

        if (responseDeepSeek != null)
        {
            Choice? choiceDeepSeek = responseDeepSeek.Choices.FirstOrDefault();

            if (choiceDeepSeek == null || choiceDeepSeek.Message == null || choiceDeepSeek.Message.Content == null)
            {
                AresLogger.Error(nameof(ConvertToChatHistoric), $"The choice or content of the message is missing.\nPrompt: {prompt}");
                return historics;
            }

            DeepSeek.Core.Models.Usage? usageDeepSeek = responseDeepSeek.Usage;

            historics.Add(new GChatHistoricModel
            (
                prompt: prompt,
                response: choiceDeepSeek.Message.Content,
                usage: new ChatValueUsage(usageDeepSeek != null ? usageDeepSeek.CompletionTokens : 0, usageDeepSeek != null ? usageDeepSeek.PromptTokens : 0)
            ));
        }

        if (responseOpenAi != null)
        {
            var contentOpenAi = responseOpenAi.Content[0];

            historics.Add(new GChatHistoricModel
            (
                prompt: prompt,
                response: contentOpenAi.Text,
                imageUrl: !string.IsNullOrWhiteSpace(imageUrl) ? contentOpenAi.ImageUri?.OriginalString : imageUrl,
                usage: new ChatValueUsage(responseOpenAi.Usage.OutputTokenCount, responseOpenAi.Usage.InputTokenCount),
                timestamp: responseOpenAi.CreatedAt.Ticks
            ));
        }

        if (imageOpenAi != null)
        {
            historics.Add(new GChatHistoricModel
            (
                prompt: prompt,
                response: imageOpenAi.RevisedPrompt,
                imageUrl: !string.IsNullOrWhiteSpace(imageUrl) ? imageOpenAi.ImageUri.OriginalString : imageUrl
            ));
        }

        return historics;
    }

    /// <summary>
    /// <b>General</b> - Constructs a Image Gen Options.
    /// </summary>
    /// <param name="optionsOpenAi">Response containing an image options by OpenAI.</param>
    public static List<ImageGenOptions> ConvertToImageGenOptions(ImageGenerationOptions? optionsOpenAi = null)
    {
        var options = new List<ImageGenOptions>();

        if (optionsOpenAi != null)
        {
            var quality = optionsOpenAi.Quality ?? GeneratedImageQuality.Standard;
            var size = optionsOpenAi.Size ?? GeneratedImageSize.W1024xH1024;
            var style = optionsOpenAi.Style ?? GeneratedImageStyle.Natural;

            try
            {
                var imageQuality = (ImageQuality)Enum.Parse(typeof(ImageQuality), quality.ToString(), ignoreCase: true);
                var imageSize = (ImageSize)Enum.Parse(typeof(ImageSize), size.ToString(), ignoreCase: true);
                var imageStyle = (ImageStyle)Enum.Parse(typeof(ImageStyle), style.ToString(), ignoreCase: true);

                options.Add(new ImageGenOptions(imageQuality, imageSize, imageStyle));
            }
            catch (ArgumentException e)
            {
                AresLogger.Error(nameof(ConvertToImageGenOptions), "Could not convert a class to ImageGenOptions.", e.Message);
            }
        }

        return options;
    }

    /// <summary>
    /// <b>Anthropic</b> - Obtém mensagens do histórico de chat da Anthropic.
    /// </summary>
    /// <param name="historics">Lista de históricos de chat armazenados.</param>
    public static List<Anthropic.SDK.Messaging.Message> GetChatAnthropicMessages(List<GChatHistoricModel>? historics)
    {
        if (historics == null || historics.Count == 0)
        {
            return new List<Anthropic.SDK.Messaging.Message>();
        }

        List<Anthropic.SDK.Messaging.Message> messages = new List<Anthropic.SDK.Messaging.Message>();

        foreach (GChatHistoricModel historic in historics)
        {
            if (!string.IsNullOrWhiteSpace(historic.Prompt))
            {
                messages.Add(new Anthropic.SDK.Messaging.Message(RoleType.User, historic.Prompt));
            }

            if (!string.IsNullOrWhiteSpace(historic.Response))
            {
                messages.Add(new Anthropic.SDK.Messaging.Message(RoleType.Assistant, historic.Response));
            }
        }

        return messages;
    }

    /// <summary>
    /// <b>Anthropic</b> - Converte um <see cref="RoleType"/> da Anthropic para um <see cref="ChatRole"/>.
    /// </summary>
    public static ChatRole ConvertAnthropicRole(RoleType role)
    {
        return role switch
        {
            RoleType.User => ChatRole.User,
            RoleType.Assistant => ChatRole.Assistant,
            _ => ChatRole.None
        };
    }

    /// <summary>
    /// <b>OpenAI</b> - Cria uma mensagem de usuário a partir do histórico.
    /// </summary>
    public static ChatMessage CreateUserMessage(GChatHistoricModel historic)
    {
        return ChatMessage.CreateUserMessage(historic.Prompt);
    }

    /// <summary>
    /// <b>OpenAI</b> - Cria uma mensagem de sistema a partir do histórico.
    /// </summary>
    public static ChatMessage? CreateSystemMessage(GChatHistoricModel historic)
    {
        return ChatMessage.CreateSystemMessage(historic.Response);
    }

    /// <summary>
    /// <b>OpenAI</b> - Obtém mensagens do histórico de chat da OpenAI.
    /// </summary>
    /// <param name="historics">Lista de históricos de chat armazenados.</param>
    public static List<ChatMessage> GetChatOpenAiMessages(List<GChatHistoricModel>? historics)
    {
        if (historics == null || historics.Count == 0)
        {
            return new List<ChatMessage>();
        }

        List<ChatMessage> messages = new List<ChatMessage>();

        foreach (GChatHistoricModel historic in historics)
        {
            if (!string.IsNullOrWhiteSpace(historic.Prompt))
            {
                messages.Add(new UserChatMessage(historic.Prompt));
            }

            if (!string.IsNullOrWhiteSpace(historic.Response))
            {
                messages.Add(new AssistantChatMessage(historic.Response));
            }
        }

        return messages;
    }

    /// <summary>
    /// <b>OpenAI</b> - Obtém as opções de geração de imagem da OpenAI.
    /// </summary>
    /// <param name="options">Opções de geração de imagem customizado.</param>
    public static ImageGenerationOptions GetImageGenerationOptions(ImageGenOptions options)
    {
        GeneratedImageQuality quality = options.Quality switch
        {
            ImageQuality.Standard => GeneratedImageQuality.Standard,
            _ => GeneratedImageQuality.High,
        };

        GeneratedImageStyle style = options.Style switch
        {
            ImageStyle.Vivid => GeneratedImageStyle.Vivid,
            _ => GeneratedImageStyle.Natural,
        };

        GeneratedImageSize size = options.Size switch
        {
            ImageSize.W1792xH1024 => GeneratedImageSize.W1792xH1024,
            ImageSize.W1024xH1792 => GeneratedImageSize.W1024xH1024,
            ImageSize.W1024xH1024 => GeneratedImageSize.W1024xH1024,
            ImageSize.W512xH512 => GeneratedImageSize.W512xH512,
            _ => GeneratedImageSize.W256xH256
        };

        return new ImageGenerationOptions()
        {
            Quality = quality,
            Style = style,
            Size = size
        };
    }

    /// <summary>
    /// <b>OpenAI</b> - Converte um <see cref="ChatMessageRole"/> da OpenAI para um <see cref="ChatRole"/>.
    /// </summary>
    public static ChatRole ConvertOpenAiRole(ChatMessageRole role)
    {
        return role switch
        {
            ChatMessageRole.System => ChatRole.System,
            ChatMessageRole.User => ChatRole.User,
            ChatMessageRole.Assistant => ChatRole.Assistant,
            _ => ChatRole.None
        };
    }

    /// <summary>
    /// <b>DeepSeek</b> - Obtém mensagens do histórico de chat da DeepSeek.
    /// </summary>
    /// <param name="historics">Lista de históricos de chat armazenados.</param>
    public static List<DeepSeek.Core.Models.Message> GetChatDeepSeekMessages(List<GChatHistoricModel>? historics)
    {
        if (historics == null || historics.Count == 0)
        {
            return new List<DeepSeek.Core.Models.Message>();
        }
        
        List<DeepSeek.Core.Models.Message> messages = new List<DeepSeek.Core.Models.Message>();

        foreach (GChatHistoricModel historic in historics)
        {
            if (!string.IsNullOrWhiteSpace(historic.Prompt))
            {
                messages.Add(DeepSeek.Core.Models.Message.NewUserMessage(historic.Prompt));
            }

            if (!string.IsNullOrWhiteSpace(historic.Response))
            {
                messages.Add(DeepSeek.Core.Models.Message.NewAssistantMessage(historic.Response));
            }
        }

        return messages;
    }

    /// <summary>
    /// <b>DeepSeek</b> - Converte um <see cref="?"/> da DeepSeek para um <see cref="ChatRole"/>.
    /// </summary>
    public static ChatRole ConvertDeepSeekRole()
    {
        return ChatRole.None;
    }
}