/*
 * Copyright (C) Rodrigo Ferreira, All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */

using Ares.Core.Objects.Chat;
using Ares.Core.Util;
using OpenAI.Chat;
using OpenAI.Images;
using System.Text.Json.Serialization;

namespace Ares.Core.Database.Model.Chat.Sub;

/// <summary>
/// Representa o histórico de conversas.
/// </summary>
public class GChatHistoricModel
{
    /// <summary>
    /// Mensagem do sistema (Normalmente a mensagem de boas-vindas ao iniciar um chat)
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("system")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string System { get; set; }

    /// <summary>
    /// Pergunta ou comando enviado pelo usuário.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("prompt")]
    public string Prompt { get; set; }

    /// <summary>
    /// Resposta gerada pela AI, se aplicável.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("response")]
    public string? Response { get; set; }

    /// <summary>
    /// URL de uma imagem gerada na conversa, se aplicável.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("imageUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ImageUrl { get; set; }

    /// <summary>
    /// Informações sobre o uso de tokens na conversa.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("usage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ChatValueUsage? Usage { get; set; }

    /// <summary>
    /// Timestamp da conversa.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("timestamp")]
    public long Timestamp { get; set; }

    /// <summary>
    /// Inicializa uma nova instância da classe <see cref="GChatHistoricModel"/>.
    /// </summary>
    /// <param name="prompt">Pergunta</param>
    /// <param name="response">Resposta ou Prompt Revisado</param>
    /// <param name="imageUrl">Opcional: Url da Image</param>
    /// <param name="usage">Uso de Tokens</param>
    /// <param name="timestamp">Timestamp da Conversa</param>
    public GChatHistoricModel(string system = "", string prompt = "", string? response = "", string? imageUrl = null, ChatValueUsage? usage = null, long timestamp = -1)
    {
        this.System = system;
        this.Prompt = prompt;
        this.Response = response;
        this.ImageUrl = imageUrl;
        this.Usage = usage;
        this.Timestamp = timestamp;

        if (timestamp == -1)
        {
            Timestamp = TimeUtil.CurrentTimeMillis();
        }
    }

    /// <summary>
    /// Constructs a chat history from a given response.
    /// </summary>
    /// <param name="prompt">Input text provided by the user.</param>
    /// <param name="imageUrl">Custom media URL, if available. (Applicable when <paramref name="responseOpenAi"/> or <paramref name="imageOpenAi"/> is not null)</param>
    /// <param name="responseOpenAi">Response generated by OpenAI's AI.</param>
    /// <param name="imageOpenAi">Response containing an image generated by OpenAI's AI.</param>
    /// <returns>A list of chat history entries.</returns>
    public static List<GChatHistoricModel> From(string prompt, string? imageUrl = null, ChatCompletion? responseOpenAi = null, GeneratedImage? imageOpenAi = null)
    {
        List<GChatHistoricModel> historics = new List<GChatHistoricModel>();

        if (responseOpenAi != null)
        {
            var contentOpenAi = responseOpenAi.Content[0];

            historics.Add(new GChatHistoricModel
            (
                prompt: prompt,
                response: contentOpenAi.Text,
                imageUrl: !string.IsNullOrWhiteSpace(imageUrl) ? contentOpenAi.ImageUri?.OriginalString : imageUrl,
                usage: new ChatValueUsage(responseOpenAi.Usage.OutputTokenCount, responseOpenAi.Usage.InputTokenCount),
                timestamp: responseOpenAi.CreatedAt.Ticks
            ));
        }

        if (imageOpenAi != null)
        {
            historics.Add(new GChatHistoricModel
            (
                prompt: prompt,
                response: imageOpenAi.RevisedPrompt,
                imageUrl: !string.IsNullOrWhiteSpace(imageUrl) ? imageOpenAi.ImageUri.OriginalString : imageUrl
            ));
        }

        return historics;
    }

    /// <summary>
    ///  Obtém mensagens do histórico de chat da OpenAI.
    /// </summary>
    /// <param name="historics">Lista de históricos de chat armazenados.</param>
    public static List<ChatMessage> ToChatOpenAiMessages(List<GChatHistoricModel>? historics)
    {
        if (historics == null || historics.Count == 0)
        {
            return new List<ChatMessage>();
        }

        List<ChatMessage> messages = new List<ChatMessage>();

        foreach (GChatHistoricModel historic in historics)
        {
            if (!string.IsNullOrWhiteSpace(historic.System))
            {
                messages.Add(new SystemChatMessage(historic.System));
            }

            if (!string.IsNullOrWhiteSpace(historic.Prompt))
            {
                messages.Add(new UserChatMessage(historic.Prompt));
            }

            if (!string.IsNullOrWhiteSpace(historic.Response))
            {
                messages.Add(new AssistantChatMessage(historic.Response));
            }
        }

        return messages;
    }

    /// <summary>
    ///  Obtém mensagens do histórico de chat da OpenAI.
    /// </summary>
    /// <param name="historics">Lista de históricos de chat armazenados.</param>
    public static List<ChatMessage> ToSystemMessage(List<GChatHistoricModel>? historics)
    {
        if (historics == null || historics.Count == 0)
        {
            return new List<ChatMessage>();
        }

        List<ChatMessage> messages = new List<ChatMessage>();

        foreach (GChatHistoricModel historic in historics)
        {
            if (!string.IsNullOrWhiteSpace(historic.Prompt))
            {
                messages.Add(new UserChatMessage(historic.Prompt));
            }

            if (!string.IsNullOrWhiteSpace(historic.Response))
            {
                messages.Add(new AssistantChatMessage(historic.Response));
            }
        }

        return messages;
    }
}