/*
 * Copyright (C) Rodrigo Ferreira, All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */

using Ares.Core.Util;
using Microsoft.Extensions.AI;
using OpenAI.Chat;
using OpenAI.Images;
using System.Text.Json.Serialization;

namespace Ares.Core.Models.Chat.Historic;

/// <summary>
/// Representa o histórico de conversas.
/// </summary>
public class UserChatHistoric
{
    /// <summary>
    /// Mensagem do sistema (Normalmente a mensagem de boas-vindas ao iniciar um chat)
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("system")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? System { get; set; }

    /// <summary>
    /// Pergunta ou comando enviado pelo usuário.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("prompt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Prompt { get; set; }

    /// <summary>
    /// Resposta gerada pela AI, se aplicável.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("response")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Response { get; set; }

    /// <summary>
    /// URL de uma imagem gerada na conversa, se aplicável.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("imageUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ImageUrl { get; set; }

    /// <summary>
    /// Informações sobre o uso de tokens na conversa.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("usage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Objects.Chat.ChatTokenUsage? Usage { get; set; }

    /// <summary>
    /// Timestamp da conversa.
    /// </summary>
    [JsonInclude]
    [JsonPropertyName("timestamp")]
    public long Timestamp { get; set; }

    /// <summary>
    /// Inicializa uma nova instância da classe <see cref="UserChatHistoric"/>.
    /// </summary>
    /// <param name="prompt">Pergunta</param>
    /// <param name="response">Resposta ou Prompt Revisado</param>
    /// <param name="imageUrl">Opcional: Url da Image</param>
    /// <param name="usage">Uso de Tokens</param>
    /// <param name="timestamp">Timestamp da Conversa</param>
    public UserChatHistoric(
            string? system = null,
            string? prompt = null,
            string? response = null,
            string? imageUrl = null,
            Objects.Chat.ChatTokenUsage? usage = null,
            long timestamp = -1)
    {
        System = system;
        Prompt = prompt;
        Response = response;
        ImageUrl = imageUrl;
        Usage = usage;
        Timestamp = timestamp;

        if (timestamp == -1)
        {
            Timestamp = TimeUtil.CurrentTimeMillis();
        }
    }

    /// <summary>
    /// Constructs a chat history from a given response.
    /// </summary>
    /// <param name="prompt">Input text provided by the user.</param>
    /// <param name="imageUrl">Custom media URL, if available. (Applicable when <paramref name="responseOpenAi"/> or <paramref name="imageOpenAi"/> is not null)</param>
    /// <param name="responseOpenAi">Response generated by OpenAI's AI.</param>
    /// <param name="imageOpenAi">Response containing an image generated by OpenAI's AI.</param>
    /// <returns>A list of chat history entries.</returns>
    public static List<UserChatHistoric> From(
        string prompt,
        string? imageUrl = null,
        ChatCompletion? responseOpenAi = null,
        GeneratedImage? imageOpenAi = null,
        ChatResponse? ollamaResponse = null)
    {
        List<UserChatHistoric> historics = new List<UserChatHistoric>();

        if (responseOpenAi != null)
        {
            var contentOpenAi = responseOpenAi.Content[0];

            historics.Add(new UserChatHistoric
            (
                prompt: prompt,
                response: contentOpenAi.Text,
                imageUrl: !string.IsNullOrWhiteSpace(imageUrl) ? contentOpenAi.ImageUri?.OriginalString : imageUrl,
                usage: new Objects.Chat.ChatTokenUsage(responseOpenAi.Usage.OutputTokenCount, responseOpenAi.Usage.InputTokenCount),
                timestamp: responseOpenAi.CreatedAt.Ticks
            ));
        }

        if (imageOpenAi != null)
        {
            historics.Add(new UserChatHistoric
            (
                prompt: prompt,
                response: imageOpenAi.RevisedPrompt,
                imageUrl: !string.IsNullOrWhiteSpace(imageUrl) ? imageOpenAi.ImageUri.OriginalString : imageUrl
            ));
        }

        if (ollamaResponse != null)
        {
            UsageDetails? usage = ollamaResponse.Usage;

            if (usage != null)
            {
                long? inputTokens = usage?.InputTokenCount;
                long? outputTokens = usage?.OutputTokenCount;

                if (inputTokens.HasValue && outputTokens.HasValue)
                {
                    historics.Add(new UserChatHistoric
                    (
                        prompt: prompt,
                        response: ollamaResponse.Text,
                        usage: new Objects.Chat.ChatTokenUsage(outputTokens.Value, inputTokens.Value),
                        timestamp: TimeUtil.CurrentTimeMillis()
                    ));
                }
            }
        }

        return historics;
    }

    /// <summary>
    ///  Obtém mensagens do histórico de chat da OpenAI.
    /// </summary>
    /// <param name="historics">Lista de históricos de chat armazenados.</param>
    public static List<OpenAI.Chat.ChatMessage> ToRemote(List<UserChatHistoric>? historics)
    {
        if (historics == null || historics.Count == 0)
        {
            return new List<OpenAI.Chat.ChatMessage>();
        }

        List<OpenAI.Chat.ChatMessage> messages = new List<OpenAI.Chat.ChatMessage>();

        foreach (UserChatHistoric historic in historics)
        {
            if (!string.IsNullOrWhiteSpace(historic.System))
            {
                messages.Add(new SystemChatMessage(historic.System));
            }

            if (!string.IsNullOrWhiteSpace(historic.Prompt))
            {
                messages.Add(new UserChatMessage(historic.Prompt));
            }

            if (!string.IsNullOrWhiteSpace(historic.Response))
            {
                messages.Add(new AssistantChatMessage(historic.Response));
            }
        }

        return messages;
    }

    /// <summary>
    ///  Obtém mensagens do histórico de chat da Ollama.
    /// </summary>
    /// <param name="historics">Lista de históricos de chat armazenados.</param>
    public static List<Microsoft.Extensions.AI.ChatMessage> ToLocal(List<UserChatHistoric>? historics)
    {
        if (historics == null || historics.Count == 0)
        {
            return new();
        }

        List<Microsoft.Extensions.AI.ChatMessage> messages = new();

        foreach (UserChatHistoric historic in historics)
        {
            if (!string.IsNullOrWhiteSpace(historic.System))
            {
                messages.Add(new Microsoft.Extensions.AI.ChatMessage(Microsoft.Extensions.AI.ChatRole.System, historic.System));
            }

            if (!string.IsNullOrWhiteSpace(historic.Prompt))
            {
                messages.Add(new Microsoft.Extensions.AI.ChatMessage(Microsoft.Extensions.AI.ChatRole.User, historic.Prompt));
            }

            if (!string.IsNullOrWhiteSpace(historic.Response))
            {
                messages.Add(new Microsoft.Extensions.AI.ChatMessage(Microsoft.Extensions.AI.ChatRole.Assistant, historic.Response));
            }
        }

        return messages;
    }
}